services:
  linkwarden:
    build: .
    container_name: Linkwarden-WEB
    restart: always
    ports:
      - 3100:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
      - meilisearch
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
      - NEXTAUTH_URL=http://localhost:3100
      - NEXTAUTH_SECRET=nextauth

  postgres:
    image: postgres:16-alpine
    container_name: Linkwarden-POSTGRES
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:linkwarden
      - POSTGRES_USER:linkwarden
      - POSTGRES_PASSWORD:password

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    container_name: Linkwarden-MEILI
    restart: always
    volumes:
      - ./meili:/meili_data
    environment:
      - MEILI_MASTER_KEY=meili